# Generated by Django 5.1.4 on 2025-10-27 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sneakers/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='menu.marca')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], max_length=10)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('U', 'Unissex'), ('I', 'Infantil')], max_length=1)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='menu.cor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='menu.produto')),
            ],
            options={
                'ordering': ('produto', 'tamanho', 'cor'),
                'unique_together': {('produto', 'tamanho', 'cor', 'genero')},
            },
        ),
    ]
